version: '3.4'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    ports:
    - 9200:9200
    volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
    - cluster.name=elasticsearch
    - xpack.monitoring.collection.enabled=true
    - xpack.security.enabled=false
    - xpack.monitoring.elasticsearch.collection.enabled=false
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms${ES_JVM_HEAP_EL} -Xmx${ES_JVM_HEAP_EL}"
    - discovery.type=single-node
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
    - elasticnet
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
    volumes:
      - logstash-data:/usr/share/logstash/data
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "9044:9044"
      - "9000:9000/tcp"
      - "9000:9000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xms${ES_JVM_HEAP_LS} -Xmx${ES_JVM_HEAP_LS}"
    networks:
      - elasticnet
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    ports:
    - 5601:5601
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    environment:
    - ELASTICSEARCH_URL=${HOST_ELASTICSEARCH_DEV}
    networks:
    - elasticnet
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status


  apm-server:
    container_name: apm-server
    image: docker.elastic.co/apm/apm-server:${ELASTIC_VERSION}
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    command: >
       apm-server -e
         -E apm-server.rum.enabled=true
         -E setup.kibana.host=kibana:5601
         -E setup.template.settings.index.number_of_replicas=0
         -E apm-server.kibana.enabled=true
         -E apm-server.kibana.host=kibana:5601
         -E output.elasticsearch.hosts=["elasticsearch:9200"]
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    environment:
      - "ELASTICSEARCH_URL=${HOST_ELASTICSEARCH_DEV}"
      - "HOST_KIBANA=${HOST_KIBANA_DEV}"
    ports:
    - 8200:8200
    networks:
    - elasticnet
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/

  metricbeat:
    container_name: metricbeat
    build: ./metricbeat
    user: root
    command: -system.hostfs=/hostfs
    environment:
      - "HOST_ELASTICSEARCH=${HOST_ELASTICSEARCH_DEV}"
      - "HOST_KIBANA=${HOST_KIBANA_DEV}"
    volumes:
      - metricbeat-data:/usr/share/metricbeat/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    networks:
      - elasticnet
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy

  heartbeat:
    container_name: heartbeat
    build: ./heartbeat
    user: root
    volumes:
      - metricbeat-data:/usr/share/heartbeat/data
    environment:
      - "HOST_ELASTICSEARCH=${HOST_ELASTICSEARCH_DEV}"
      - "HOST_KIBANA=${HOST_KIBANA_DEV}"
    networks:
      - elasticnet
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy

networks:
  elasticnet:
    driver: bridge

volumes:
  elasticsearch-data:
  heartbeat-data:
    driver: local
  metricbeat-data:
    driver: local
  logstash-data:
    driver: local